// Code generated by protoc-gen-go.
// source: entry.proto
// DO NOT EDIT!

/*
Package categolj3 is a generated protocol buffer package.

It is generated from these files:
	entry.proto

It has these top-level messages:
	Entry
	EntryPage
*/
package categolj3

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Entry struct {
	EntryId          *int64             `protobuf:"varint,1,req,name=entryId" json:"entryId,omitempty"`
	Content          *string            `protobuf:"bytes,2,opt,name=content" json:"content,omitempty"`
	Created          *Entry_Author      `protobuf:"bytes,3,req,name=created" json:"created,omitempty"`
	Updated          *Entry_Author      `protobuf:"bytes,4,req,name=updated" json:"updated,omitempty"`
	FrontMatter      *Entry_FrontMatter `protobuf:"bytes,5,req,name=frontMatter" json:"frontMatter,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *Entry) Reset()                    { *m = Entry{} }
func (m *Entry) String() string            { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()               {}
func (*Entry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Entry) GetEntryId() int64 {
	if m != nil && m.EntryId != nil {
		return *m.EntryId
	}
	return 0
}

func (m *Entry) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

func (m *Entry) GetCreated() *Entry_Author {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *Entry) GetUpdated() *Entry_Author {
	if m != nil {
		return m.Updated
	}
	return nil
}

func (m *Entry) GetFrontMatter() *Entry_FrontMatter {
	if m != nil {
		return m.FrontMatter
	}
	return nil
}

type Entry_Author struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Date             *int64  `protobuf:"varint,2,req,name=date" json:"date,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Entry_Author) Reset()                    { *m = Entry_Author{} }
func (m *Entry_Author) String() string            { return proto.CompactTextString(m) }
func (*Entry_Author) ProtoMessage()               {}
func (*Entry_Author) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *Entry_Author) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Entry_Author) GetDate() int64 {
	if m != nil && m.Date != nil {
		return *m.Date
	}
	return 0
}

type Entry_FrontMatter struct {
	Title            *string  `protobuf:"bytes,1,req,name=title" json:"title,omitempty"`
	Tags             []string `protobuf:"bytes,2,rep,name=tags" json:"tags,omitempty"`
	Categories       []string `protobuf:"bytes,3,rep,name=categories" json:"categories,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Entry_FrontMatter) Reset()                    { *m = Entry_FrontMatter{} }
func (m *Entry_FrontMatter) String() string            { return proto.CompactTextString(m) }
func (*Entry_FrontMatter) ProtoMessage()               {}
func (*Entry_FrontMatter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 1} }

func (m *Entry_FrontMatter) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *Entry_FrontMatter) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Entry_FrontMatter) GetCategories() []string {
	if m != nil {
		return m.Categories
	}
	return nil
}

type EntryPage struct {
	Content          []*Entry `protobuf:"bytes,1,rep,name=content" json:"content,omitempty"`
	TotalPages       *int64   `protobuf:"varint,2,req,name=totalPages" json:"totalPages,omitempty"`
	TotalElements    *int64   `protobuf:"varint,3,req,name=totalElements" json:"totalElements,omitempty"`
	First            *bool    `protobuf:"varint,4,req,name=first" json:"first,omitempty"`
	Last             *bool    `protobuf:"varint,5,req,name=last" json:"last,omitempty"`
	NumberOfElements *int64   `protobuf:"varint,6,req,name=numberOfElements" json:"numberOfElements,omitempty"`
	Size             *int32   `protobuf:"varint,7,req,name=size" json:"size,omitempty"`
	Number           *int32   `protobuf:"varint,8,req,name=number" json:"number,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *EntryPage) Reset()                    { *m = EntryPage{} }
func (m *EntryPage) String() string            { return proto.CompactTextString(m) }
func (*EntryPage) ProtoMessage()               {}
func (*EntryPage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *EntryPage) GetContent() []*Entry {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *EntryPage) GetTotalPages() int64 {
	if m != nil && m.TotalPages != nil {
		return *m.TotalPages
	}
	return 0
}

func (m *EntryPage) GetTotalElements() int64 {
	if m != nil && m.TotalElements != nil {
		return *m.TotalElements
	}
	return 0
}

func (m *EntryPage) GetFirst() bool {
	if m != nil && m.First != nil {
		return *m.First
	}
	return false
}

func (m *EntryPage) GetLast() bool {
	if m != nil && m.Last != nil {
		return *m.Last
	}
	return false
}

func (m *EntryPage) GetNumberOfElements() int64 {
	if m != nil && m.NumberOfElements != nil {
		return *m.NumberOfElements
	}
	return 0
}

func (m *EntryPage) GetSize() int32 {
	if m != nil && m.Size != nil {
		return *m.Size
	}
	return 0
}

func (m *EntryPage) GetNumber() int32 {
	if m != nil && m.Number != nil {
		return *m.Number
	}
	return 0
}

func init() {
	proto.RegisterType((*Entry)(nil), "categolj3.Entry")
	proto.RegisterType((*Entry_Author)(nil), "categolj3.Entry.Author")
	proto.RegisterType((*Entry_FrontMatter)(nil), "categolj3.Entry.FrontMatter")
	proto.RegisterType((*EntryPage)(nil), "categolj3.EntryPage")
}

var fileDescriptor0 = []byte{
	// 321 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x91, 0xd1, 0x4e, 0xf2, 0x40,
	0x10, 0x85, 0x53, 0x4a, 0x81, 0xce, 0xfe, 0xfc, 0x92, 0x4d, 0xd4, 0x0d, 0xf1, 0x02, 0x89, 0x89,
	0x5c, 0x35, 0x11, 0xef, 0x4d, 0x24, 0xc1, 0xc4, 0x0b, 0x23, 0xaf, 0xb0, 0xc2, 0x82, 0xd5, 0xb6,
	0x4b, 0x76, 0x87, 0x0b, 0x7d, 0x10, 0x1f, 0xc3, 0x67, 0x74, 0x76, 0x6a, 0xa0, 0xd1, 0xc4, 0xcb,
	0x73, 0xfa, 0x9d, 0x99, 0xb3, 0x53, 0x10, 0xa6, 0x42, 0xf7, 0x96, 0x6d, 0x9d, 0x45, 0x2b, 0xd3,
	0xa5, 0x46, 0xb3, 0xb1, 0xc5, 0xcb, 0xf5, 0xf8, 0xa3, 0x05, 0xc9, 0x3c, 0x7c, 0x92, 0x47, 0xd0,
	0x65, 0xe6, 0x7e, 0xa5, 0xa2, 0x51, 0x6b, 0x12, 0x07, 0x63, 0x69, 0x2b, 0x24, 0x53, 0xb5, 0x46,
	0xd1, 0x24, 0x95, 0x13, 0x32, 0x9c, 0xa1, 0xe8, 0x4a, 0xc5, 0x44, 0x88, 0xe9, 0x69, 0xb6, 0x1f,
	0x94, 0xf1, 0x90, 0xec, 0x76, 0x87, 0xcf, 0xd6, 0x05, 0x72, 0xb7, 0x5d, 0x31, 0xd9, 0xfe, 0x9b,
	0xbc, 0x02, 0xb1, 0x76, 0xb4, 0xe5, 0x41, 0x23, 0x1a, 0xa7, 0x12, 0xa6, 0xcf, 0x7e, 0xd1, 0x77,
	0x07, 0x66, 0x78, 0x01, 0x9d, 0xef, 0xf0, 0x3f, 0x68, 0x57, 0xba, 0x34, 0xdc, 0x37, 0x0d, 0x2a,
	0xac, 0xa4, 0xb2, 0xd4, 0x7e, 0x78, 0x03, 0xa2, 0x11, 0x92, 0x7d, 0x48, 0x30, 0xc7, 0xa2, 0xc1,
	0xa2, 0xde, 0x78, 0x62, 0x63, 0x52, 0x12, 0xa0, 0x5e, 0xe8, 0x72, 0xe3, 0xe9, 0x6d, 0xe4, 0x8d,
	0x3f, 0x23, 0x48, 0x79, 0xf7, 0x42, 0x6f, 0x8c, 0x3c, 0x3f, 0xdc, 0x22, 0xa2, 0xcf, 0x62, 0x3a,
	0xf8, 0x59, 0x31, 0x0c, 0x41, 0x8b, 0xba, 0x08, 0xbc, 0xaf, 0x4b, 0xc8, 0x63, 0xe8, 0xb3, 0x37,
	0x2f, 0x4c, 0x49, 0x59, 0xcf, 0x77, 0x8b, 0x43, 0x99, 0x75, 0xee, 0x3c, 0xf2, 0x71, 0x7a, 0xa1,
	0x4c, 0xa1, 0x49, 0x25, 0xac, 0x14, 0x0c, 0xaa, 0x5d, 0xf9, 0x64, 0xdc, 0xe3, 0x7a, 0x1f, 0xeb,
	0x70, 0x8c, 0x38, 0x9f, 0xbf, 0x1b, 0xd5, 0x25, 0x95, 0xc8, 0xff, 0xd0, 0xa9, 0x39, 0xd5, 0x0b,
	0x7a, 0x76, 0x09, 0x27, 0xba, 0xcc, 0xf2, 0xd7, 0x46, 0x31, 0xfe, 0xdb, 0x7e, 0x26, 0xea, 0x77,
	0xb0, 0x58, 0x44, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xfb, 0xc4, 0x61, 0xee, 0x0b, 0x02, 0x00,
	0x00,
}
